/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\a学习文件\\vuepress\\docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-9b5d2016",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9b5d2016").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-4c0267ce",
    path: "/css/css-a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c0267ce").then(next)
    },
  },
  {
    name: "v-a3f0adb4",
    path: "/chang.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a3f0adb4").then(next)
    },
  },
  {
    name: "v-026b53ea",
    path: "/language/chinese/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-026b53ea").then(next)
    },
  },
  {
    path: "/language/chinese/index.html",
    redirect: "/language/chinese/"
  },
  {
    name: "v-5ee7fae3",
    path: "/language/japanese/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ee7fae3").then(next)
    },
  },
  {
    path: "/language/japanese/index.html",
    redirect: "/language/japanese/"
  },
  {
    name: "v-aa6daed0",
    path: "/language/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aa6daed0").then(next)
    },
  },
  {
    path: "/language/index.html",
    redirect: "/language/"
  },
  {
    name: "v-7050ca26",
    path: "/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7050ca26").then(next)
    },
  },
  {
    name: "v-ad43f30e",
    path: "/css/css-b.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ad43f30e").then(next)
    },
  },
  {
    name: "v-3648cc7a",
    path: "/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3648cc7a").then(next)
    },
  },
  {
    path: "/css/index.html",
    redirect: "/css/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]