/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "青鸟飞鱼",
  "description": "青鸟飞鱼的博客",
  "base": "/docs/",
  "headTags": [
    [
      "meta",
      {
        "name": "author",
        "content": "青鸟飞鱼"
      }
    ],
    [
      "meta",
      {
        "name": "Keywords",
        "content": "青鸟飞鱼各自生活永不相见"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "/docs/favicon.ico"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/docs/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/docs/icons/apple-touch-icon-152x152.png"
      }
    ],
    [
      "link",
      {
        "rel": "mask-icon",
        "href": "/docs/icons/safari-pinned-tab.svg",
        "color": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileImage",
        "content": "/icons/msapplication-icon-144x144.png"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#000000"
      }
    ]
  ],
  "pages": [
    {
      "title": "Hello VuePress!",
      "frontmatter": {
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-9b5d2016",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "PWA",
          "slug": "pwa"
        }
      ],
      "lastUpdated": "2022年7月4日星期一晚上8点13分",
      "lastUpdatedTimestamp": 1656936839000
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-7050ca26",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        }
      ],
      "lastUpdated": "2022年7月4日星期一下午3点20分",
      "lastUpdatedTimestamp": 1656919221000
    },
    {
      "title": "chang",
      "frontmatter": {},
      "regularPath": "/chang.html",
      "relativePath": "chang.md",
      "key": "v-a3f0adb4",
      "path": "/chang.html",
      "headers": [
        {
          "level": 2,
          "title": "chang",
          "slug": "chang"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "1.二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 3,
          "title": "2.二级标题",
          "slug": "_2-二级标题"
        },
        {
          "level": 3,
          "title": "3.二级标题",
          "slug": "_3-二级标题"
        },
        {
          "level": 3,
          "title": "4.二级标题",
          "slug": "_4-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-2"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-3"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-4"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-5"
        }
      ],
      "lastUpdated": "2022年7月4日星期一下午3点20分",
      "lastUpdatedTimestamp": 1656919221000
    },
    {
      "frontmatter": {
        "titlt": "css的主页面"
      },
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-3648cc7a",
      "path": "/css/",
      "lastUpdated": "2022年7月4日星期一下午3点20分",
      "lastUpdatedTimestamp": 1656919221000
    },
    {
      "title": "asdad",
      "frontmatter": {},
      "regularPath": "/language/",
      "relativePath": "language/README.md",
      "key": "v-aa6daed0",
      "path": "/language/",
      "lastUpdated": "2022年7月4日星期一下午3点20分",
      "lastUpdatedTimestamp": 1656919221000
    },
    {
      "frontmatter": {
        "titlt": "css下面的a页面"
      },
      "regularPath": "/css/css-a.html",
      "relativePath": "css/css-a.md",
      "key": "v-4c0267ce",
      "path": "/css/css-a.html",
      "lastUpdated": "2022年7月4日星期一下午3点20分",
      "lastUpdatedTimestamp": 1656919221000
    },
    {
      "frontmatter": {
        "navbar": false
      },
      "regularPath": "/language/japanese/",
      "relativePath": "language/japanese/README.md",
      "key": "v-5ee7fae3",
      "path": "/language/japanese/",
      "lastUpdated": "2022年7月4日星期一下午3点20分",
      "lastUpdatedTimestamp": 1656919221000
    },
    {
      "title": "中火花",
      "frontmatter": {},
      "regularPath": "/language/chinese/",
      "relativePath": "language/chinese/README.md",
      "key": "v-026b53ea",
      "path": "/language/chinese/",
      "headers": [
        {
          "level": 2,
          "title": "中火花",
          "slug": "中火花"
        }
      ],
      "lastUpdated": "2022年7月4日星期一晚上8点26分",
      "lastUpdatedTimestamp": 1656937577000
    },
    {
      "frontmatter": {
        "titlt": "css下面的b页面"
      },
      "regularPath": "/css/css-b.html",
      "relativePath": "css/css-b.md",
      "key": "v-ad43f30e",
      "path": "/css/css-b.html",
      "lastUpdated": "2022年7月4日星期一下午3点20分",
      "lastUpdatedTimestamp": 1656919221000
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "sidebar": [
      "/",
      "/about",
      "/language/chinese/",
      {
        "title": "分组标题css",
        "path": "/css/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/css/css-a",
          "/css/css-b"
        ]
      }
    ],
    "logo": "/assets/img/hero.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Chang",
        "link": "/chang.html"
      },
      {
        "text": "External",
        "link": "https://google.com"
      },
      {
        "text": "Languages",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/"
          }
        ]
      }
    ]
  }
}